# アプリ名
spring.application.name=book-management

# H2コンソールをブラウザで使えるようにする
spring.h2.console.enabled=true

# DBの場所を "testdb" という名前に固定する
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernateが自動でテーブルを作成するようにする
spring.jpa.hibernate.ddl-auto=update